server:
  port: 8083

security:
  basic:
    enabled: false
  oauth2:
    resource:
      id: resource1
      user-info-uri: http://localhost:8080/user

logging:
  level:
    org.springframework.security: DEBUG
