security:
  user:
    name: greg
    password: turnquist
  oauth2:
    client:
      client-id: foo
      client-secret: bar
    authorization:
      checkTokenAccess: isAuthenticated()

logging:
  level:
    org.springframework.security: DEBUG
